title: 
description: "Learning hub for HTML, CSS, JS, and C#"
theme: minima

just_the_docs:
  nav:
    - title: HTML
      url: html
    - title: CSS
      url: css
    - title: JS
      url: js
    - title: C#
      url: csharp
